// Generated by scripts/build-client.mjs; edit client/index.mjs instead.
window.__ModuleLoader__.load({
  id: 'dsh-short-tool-ids',
  factory: (function createClientPlugin(require) {
  const React = require('react');
  const { createElement: h, useEffect, useId, useMemo, useRef, useState, useSyncExternalStore } = React;
  const namespace = 'short-tool-ids';
  const inject = ['slots', 'settingsScope'];

  function ShortIdsToggle({ provider, scope }) {
    const reader = useMemo(() => ({
      subscribe: listener => scope.subscribe(listener),
      getSnapshot: () => scope.getSnapshot(),
    }), [scope]);
    const snapshot = useSyncExternalStore(reader.subscribe, reader.getSnapshot, reader.getSnapshot);
    const [pending, setPending] = useState(false);
    const [error, setError] = useState('');
    const busy = useRef(false);
    const mounted = useRef(true);
    useEffect(() => {
      mounted.current = true;
      return () => { mounted.current = false; };
    }, []);
    const hintId = useId();
    const errorId = useId();
    const route = provider.provider;
    const checked = Object.hasOwn(snapshot.value?.providers ?? {}, route)
      && snapshot.value.providers[route] === true;
    const writable = snapshot.status === 'ready' && snapshot.writable && snapshot.mode === 'host';

    async function change(event) {
      if (!writable || busy.current) return;
      const next = event.currentTarget.checked === true;
      busy.current = true;
      setPending(true);
      setError('');
      try {
        // Fence the rendered snapshot; the scope owns serialization, recovery,
        // and the shared mirror that refreshes every occurrence of this card.
        await scope.mutate([{ op: 'set', path: ['providers', route], value: next }], snapshot.revision);
        // This installed scope recovers {ok:false} responses without rejecting.
        // Confirm the mirrored value instead of treating settlement as success.
        const settled = scope.getSnapshot();
        if (settled.status !== 'ready' || settled.value?.providers?.[route] !== next) {
          throw new Error('Setting was not confirmed');
        }
      } catch {
        // Never render raw transport errors: only this namespace is relevant,
        // and server diagnostics can contain configuration details.
        if (mounted.current) setError('Could not save this setting. It may have changed elsewhere. Review the current value and try again.');
      } finally {
        busy.current = false;
        if (mounted.current) setPending(false);
      }
    }

    return h('div', { style: { padding: '12px 0', fontSize: '13px' } },
      h('label', { style: { display: 'flex', alignItems: 'center', gap: '8px' } },
        h('input', {
          type: 'checkbox', checked, disabled: !writable || pending,
          onChange: change, 'aria-busy': pending,
          'aria-describedby': error ? `${hintId} ${errorId}` : hintId,
        }),
        h('span', null, 'Use short tool-call IDs')),
      h('aside', {
        id: hintId, role: 'note', 'aria-label': 'About short tool-call IDs',
        style: {
          margin: '10px 0 0', padding: '10px 12px', minWidth: 0,
          border: '1px solid var(--dsw-alias-border-l3)',
          borderInlineStart: '3px solid var(--dsw-alias-state-warn-label)',
          borderRadius: '8px', maxWidth: '520px', boxSizing: 'border-box',
          fontSize: '12px', lineHeight: '18px', overflowWrap: 'anywhere',
          color: 'var(--dsw-alias-label-secondary)',
        },
      },
        h('strong', { style: {
          display: 'block', marginBottom: '4px', fontWeight: 600,
          color: 'var(--dsw-alias-state-warn-label)',
        } }, 'Experimental workaround'),
        h('p', { style: { margin: 0 } },
          'Enable only if this provider rejects long tool-call IDs. Shortens outgoing IDs to 64 characters or fewer for Chat Completions; saved history stays unchanged.'),
        h('p', { style: { margin: '4px 0 0', color: 'var(--dsw-alias-label-tertiary)' } },
          'Other protocols are not supported. Compatibility is not guaranteed.')), 
      !writable ? h('p', { role: 'status', style: { margin: '6px 0 0' } },
        snapshot.status === 'loading' ? 'Loading setting…' : 'This setting is unavailable or read-only.') : null,
      pending ? h('p', { role: 'status', style: { margin: '6px 0 0' } }, 'Saving…') : null,
      error ? h('p', { id: errorId, role: 'alert', style: { margin: '6px 0 0' } }, error) : null);
  }

  function apply(ctx) {
    // bind() belongs to this calling fiber; it owns subscription/write teardown.
    const scope = ctx.settingsScope.bind({ namespace });
    ctx.slots.inject('settings.models.provider-card', () => ctx.slots.register({
      name: 'settings.models.provider-card',
      key: 'llm-pi-ai',
      inject: () => ({ scope }),
    }, ShortIdsToggle));
  }

  return { inject, apply };
})
});
