import { mkdir, writeFile } from 'node:fs/promises';
import { createClientPlugin } from '../client/index.mjs';

// The installed DSH serves lazy factory registrations, not ESM modules. Keep
// require('react') inside materialization so it uses the GUI's React singleton.
const output = new URL('../lib/client.js', import.meta.url);
const bundle = `// Generated by scripts/build-client.mjs; edit client/index.mjs instead.\nwindow.__ModuleLoader__.load({\n  id: 'dsh-short-tool-ids',\n  factory: (${createClientPlugin.toString()})\n});\n`;
await mkdir(new URL('../lib/', import.meta.url), { recursive: true });
await writeFile(output, bundle, 'utf8');
console.log(`Built ${output.pathname}`);
